apiVersion: v1
kind: Service
metadata:
  name: python-django-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sample-python-app
  ports:
    - port: 80
      targetPort: 8000
      # Optional field
      nodePort: 30007
